export const FETCH_FILES = 'FETCH_FILES';
export const FETCH_FILES_FAILED = 'FETCH_FILES_FAILED';

export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';
export const GET_EMPLOYEE_DETAILS = 'GET_EMPLOYEE_DETAILS';



